(cl:defpackage rctestpkg-srv
  (:use )
  (:export
   "MPC_CC"
   "<MPC_CC-REQUEST>"
   "MPC_CC-REQUEST"
   "<MPC_CC-RESPONSE>"
   "MPC_CC-RESPONSE"
   "MULTTWOINTS"
   "<MULTTWOINTS-REQUEST>"
   "MULTTWOINTS-REQUEST"
   "<MULTTWOINTS-RESPONSE>"
   "MULTTWOINTS-RESPONSE"
   "MPC_LK"
   "<MPC_LK-REQUEST>"
   "MPC_LK-REQUEST"
   "<MPC_LK-RESPONSE>"
   "MPC_LK-RESPONSE"
  ))

