(cl:in-package rctestpkg-srv)
(cl:export '(U0-VAL
          U0
          H0-VAL
          H0
          VL-VAL
          VL
          I0-VAL
          I0
          WV-VAL
          WV
          WH-VAL
          WH
          WI-VAL
          WI
          H_STOP-VAL
          H_STOP
          T_GAP-VAL
          T_GAP
          V_MAX-VAL
          V_MAX
          V_MIN-VAL
          V_MIN
          H_MIN-VAL
          H_MIN
          I_MAX-VAL
          I_MAX
          I_MIN-VAL
          I_MIN
          I-VAL
          I
))