(cl:in-package rctestpkg-srv)
(cl:export '(Y0-VAL
          Y0
          V0-VAL
          V0
          P0-VAL
          P0
          R0-VAL
          R0
          S0-VAL
          S0
          WY-VAL
          WY
          WV-VAL
          WV
          WP-VAL
          WP
          WR-VAL
          WR
          WS-VAL
          WS
          Y_MAX-VAL
          Y_MAX
          Y_MIN-VAL
          Y_MIN
          V_MAX-VAL
          V_MAX
          P_MAX-VAL
          P_MAX
          R_MAX-VAL
          R_MAX
          S_MAX-VAL
          S_MAX
          A-VAL
          A
          B-VAL
          B
          E-VAL
          E
          RD-VAL
          RD
          S-VAL
          S
))