// Generated by gencpp from file rctestpkg/currentTime.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_CURRENTTIME_H
#define RCTESTPKG_MESSAGE_CURRENTTIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rctestpkg
{
template <class ContainerAllocator>
struct currentTime_
{
  typedef currentTime_<ContainerAllocator> Type;

  currentTime_()
    : time(0)  {
    }
  currentTime_(const ContainerAllocator& _alloc)
    : time(0)  {
  (void)_alloc;
    }



   typedef int64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::rctestpkg::currentTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rctestpkg::currentTime_<ContainerAllocator> const> ConstPtr;

}; // struct currentTime_

typedef ::rctestpkg::currentTime_<std::allocator<void> > currentTime;

typedef boost::shared_ptr< ::rctestpkg::currentTime > currentTimePtr;
typedef boost::shared_ptr< ::rctestpkg::currentTime const> currentTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rctestpkg::currentTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rctestpkg::currentTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rctestpkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rctestpkg': ['/home/ubuntu/phil_catkin_ws/src/rctestpkg/msg'], 'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::currentTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::currentTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::currentTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::currentTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::currentTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::currentTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rctestpkg::currentTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50be640c11c45b7adcb0b6b7fbf3f928";
  }

  static const char* value(const ::rctestpkg::currentTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50be640c11c45b7aULL;
  static const uint64_t static_value2 = 0xdcb0b6b7fbf3f928ULL;
};

template<class ContainerAllocator>
struct DataType< ::rctestpkg::currentTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rctestpkg/currentTime";
  }

  static const char* value(const ::rctestpkg::currentTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rctestpkg::currentTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 time\n\
";
  }

  static const char* value(const ::rctestpkg::currentTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rctestpkg::currentTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct currentTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rctestpkg::currentTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rctestpkg::currentTime_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCTESTPKG_MESSAGE_CURRENTTIME_H
