// Generated by gencpp from file rctestpkg/LKdata.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_LKDATA_H
#define RCTESTPKG_MESSAGE_LKDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rctestpkg
{
template <class ContainerAllocator>
struct LKdata_
{
  typedef LKdata_<ContainerAllocator> Type;

  LKdata_()
    : y(0.0)
    , vl(0.0)
    , phi(0.0)
    , r(0.0)
    , rd(0.0)  {
    }
  LKdata_(const ContainerAllocator& _alloc)
    : y(0.0)
    , vl(0.0)
    , phi(0.0)
    , r(0.0)
    , rd(0.0)  {
  (void)_alloc;
    }



   typedef double _y_type;
  _y_type y;

   typedef double _vl_type;
  _vl_type vl;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _r_type;
  _r_type r;

   typedef double _rd_type;
  _rd_type rd;




  typedef boost::shared_ptr< ::rctestpkg::LKdata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rctestpkg::LKdata_<ContainerAllocator> const> ConstPtr;

}; // struct LKdata_

typedef ::rctestpkg::LKdata_<std::allocator<void> > LKdata;

typedef boost::shared_ptr< ::rctestpkg::LKdata > LKdataPtr;
typedef boost::shared_ptr< ::rctestpkg::LKdata const> LKdataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rctestpkg::LKdata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rctestpkg::LKdata_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rctestpkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rctestpkg': ['/home/ubuntu/phil_catkin_ws/src/rctestpkg/msg'], 'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::LKdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::LKdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::LKdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::LKdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::LKdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::LKdata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rctestpkg::LKdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e0ad131c0d1bef35b3e8e9fd510b179";
  }

  static const char* value(const ::rctestpkg::LKdata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e0ad131c0d1bef3ULL;
  static const uint64_t static_value2 = 0x5b3e8e9fd510b179ULL;
};

template<class ContainerAllocator>
struct DataType< ::rctestpkg::LKdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rctestpkg/LKdata";
  }

  static const char* value(const ::rctestpkg::LKdata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rctestpkg::LKdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# LK data: includes y-position, lateral velocity, yaw angle, yaw rate, and road curvature\n\
float64 y\n\
float64 vl\n\
float64 phi\n\
float64 r\n\
float64 rd\n\
";
  }

  static const char* value(const ::rctestpkg::LKdata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rctestpkg::LKdata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
      stream.next(m.vl);
      stream.next(m.phi);
      stream.next(m.r);
      stream.next(m.rd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LKdata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rctestpkg::LKdata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rctestpkg::LKdata_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "vl: ";
    Printer<double>::stream(s, indent + "  ", v.vl);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "rd: ";
    Printer<double>::stream(s, indent + "  ", v.rd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCTESTPKG_MESSAGE_LKDATA_H
