// Generated by gencpp from file rctestpkg/MPC_ACC.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_MPC_ACC_H
#define RCTESTPKG_MESSAGE_MPC_ACC_H

#include <ros/service_traits.h>


#include <rctestpkg/MPC_ACCRequest.h>
#include <rctestpkg/MPC_ACCResponse.h>


namespace rctestpkg
{

struct MPC_ACC
{

typedef MPC_ACCRequest Request;
typedef MPC_ACCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MPC_ACC
} // namespace rctestpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rctestpkg::MPC_ACC > {
  static const char* value()
  {
    return "cf39216e8627c9fbf3a389da0b0de171";
  }

  static const char* value(const ::rctestpkg::MPC_ACC&) { return value(); }
};

template<>
struct DataType< ::rctestpkg::MPC_ACC > {
  static const char* value()
  {
    return "rctestpkg/MPC_ACC";
  }

  static const char* value(const ::rctestpkg::MPC_ACC&) { return value(); }
};


// service_traits::MD5Sum< ::rctestpkg::MPC_ACCRequest> should match 
// service_traits::MD5Sum< ::rctestpkg::MPC_ACC > 
template<>
struct MD5Sum< ::rctestpkg::MPC_ACCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MPC_ACC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_ACCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MPC_ACCRequest> should match 
// service_traits::DataType< ::rctestpkg::MPC_ACC > 
template<>
struct DataType< ::rctestpkg::MPC_ACCRequest>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MPC_ACC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_ACCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rctestpkg::MPC_ACCResponse> should match 
// service_traits::MD5Sum< ::rctestpkg::MPC_ACC > 
template<>
struct MD5Sum< ::rctestpkg::MPC_ACCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MPC_ACC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_ACCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MPC_ACCResponse> should match 
// service_traits::DataType< ::rctestpkg::MPC_ACC > 
template<>
struct DataType< ::rctestpkg::MPC_ACCResponse>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MPC_ACC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_ACCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCTESTPKG_MESSAGE_MPC_ACC_H
