// Generated by gencpp from file rctestpkg/MultTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_MULTTWOINTSRESPONSE_H
#define RCTESTPKG_MESSAGE_MULTTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rctestpkg
{
template <class ContainerAllocator>
struct MultTwoIntsResponse_
{
  typedef MultTwoIntsResponse_<ContainerAllocator> Type;

  MultTwoIntsResponse_()
    : product(0)  {
    }
  MultTwoIntsResponse_(const ContainerAllocator& _alloc)
    : product(0)  {
  (void)_alloc;
    }



   typedef int64_t _product_type;
  _product_type product;




  typedef boost::shared_ptr< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultTwoIntsResponse_

typedef ::rctestpkg::MultTwoIntsResponse_<std::allocator<void> > MultTwoIntsResponse;

typedef boost::shared_ptr< ::rctestpkg::MultTwoIntsResponse > MultTwoIntsResponsePtr;
typedef boost::shared_ptr< ::rctestpkg::MultTwoIntsResponse const> MultTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rctestpkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rctestpkg': ['/home/ubuntu/phil_catkin_ws/src/rctestpkg/msg'], 'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0999a385a89125a9804d02fa52c82670";
  }

  static const char* value(const ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0999a385a89125a9ULL;
  static const uint64_t static_value2 = 0x804d02fa52c82670ULL;
};

template<class ContainerAllocator>
struct DataType< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rctestpkg/MultTwoIntsResponse";
  }

  static const char* value(const ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 product\n\
\n\
";
  }

  static const char* value(const ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.product);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rctestpkg::MultTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "product: ";
    Printer<int64_t>::stream(s, indent + "  ", v.product);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCTESTPKG_MESSAGE_MULTTWOINTSRESPONSE_H
