# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rctestpkg/Motor_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Motor_data(genpy.Message):
  _md5sum = "52f2e122b08e43f7a7e3b1d033bdba18"
  _type = "rctestpkg/Motor_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 position
int64 countPerSecond
float64 current
float64 h
float64 hdot
"""
  __slots__ = ['position','countPerSecond','current','h','hdot']
  _slot_types = ['int64','int64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,countPerSecond,current,h,hdot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Motor_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = 0
      if self.countPerSecond is None:
        self.countPerSecond = 0
      if self.current is None:
        self.current = 0.
      if self.h is None:
        self.h = 0.
      if self.hdot is None:
        self.hdot = 0.
    else:
      self.position = 0
      self.countPerSecond = 0
      self.current = 0.
      self.h = 0.
      self.hdot = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2q3d.pack(_x.position, _x.countPerSecond, _x.current, _x.h, _x.hdot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.position, _x.countPerSecond, _x.current, _x.h, _x.hdot,) = _struct_2q3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2q3d.pack(_x.position, _x.countPerSecond, _x.current, _x.h, _x.hdot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.position, _x.countPerSecond, _x.current, _x.h, _x.hdot,) = _struct_2q3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2q3d = struct.Struct("<2q3d")
