// Generated by gencpp from file rctestpkg/MultTwoInts.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_MULTTWOINTS_H
#define RCTESTPKG_MESSAGE_MULTTWOINTS_H

#include <ros/service_traits.h>


#include <rctestpkg/MultTwoIntsRequest.h>
#include <rctestpkg/MultTwoIntsResponse.h>


namespace rctestpkg
{

struct MultTwoInts
{

typedef MultTwoIntsRequest Request;
typedef MultTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultTwoInts
} // namespace rctestpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rctestpkg::MultTwoInts > {
  static const char* value()
  {
    return "1f3af93331fc1032113dd90d9a5f0755";
  }

  static const char* value(const ::rctestpkg::MultTwoInts&) { return value(); }
};

template<>
struct DataType< ::rctestpkg::MultTwoInts > {
  static const char* value()
  {
    return "rctestpkg/MultTwoInts";
  }

  static const char* value(const ::rctestpkg::MultTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::rctestpkg::MultTwoIntsRequest> should match 
// service_traits::MD5Sum< ::rctestpkg::MultTwoInts > 
template<>
struct MD5Sum< ::rctestpkg::MultTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MultTwoInts >::value();
  }
  static const char* value(const ::rctestpkg::MultTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MultTwoIntsRequest> should match 
// service_traits::DataType< ::rctestpkg::MultTwoInts > 
template<>
struct DataType< ::rctestpkg::MultTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MultTwoInts >::value();
  }
  static const char* value(const ::rctestpkg::MultTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rctestpkg::MultTwoIntsResponse> should match 
// service_traits::MD5Sum< ::rctestpkg::MultTwoInts > 
template<>
struct MD5Sum< ::rctestpkg::MultTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MultTwoInts >::value();
  }
  static const char* value(const ::rctestpkg::MultTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MultTwoIntsResponse> should match 
// service_traits::DataType< ::rctestpkg::MultTwoInts > 
template<>
struct DataType< ::rctestpkg::MultTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MultTwoInts >::value();
  }
  static const char* value(const ::rctestpkg::MultTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCTESTPKG_MESSAGE_MULTTWOINTS_H
