// Generated by gencpp from file rctestpkg/ComputeControl.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_COMPUTECONTROL_H
#define RCTESTPKG_MESSAGE_COMPUTECONTROL_H

#include <ros/service_traits.h>


#include <rctestpkg/ComputeControlRequest.h>
#include <rctestpkg/ComputeControlResponse.h>


namespace rctestpkg
{

struct ComputeControl
{

typedef ComputeControlRequest Request;
typedef ComputeControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeControl
} // namespace rctestpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rctestpkg::ComputeControl > {
  static const char* value()
  {
    return "99cbc1e3badf94dc8e3459eb691661ab";
  }

  static const char* value(const ::rctestpkg::ComputeControl&) { return value(); }
};

template<>
struct DataType< ::rctestpkg::ComputeControl > {
  static const char* value()
  {
    return "rctestpkg/ComputeControl";
  }

  static const char* value(const ::rctestpkg::ComputeControl&) { return value(); }
};


// service_traits::MD5Sum< ::rctestpkg::ComputeControlRequest> should match 
// service_traits::MD5Sum< ::rctestpkg::ComputeControl > 
template<>
struct MD5Sum< ::rctestpkg::ComputeControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::ComputeControl >::value();
  }
  static const char* value(const ::rctestpkg::ComputeControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::ComputeControlRequest> should match 
// service_traits::DataType< ::rctestpkg::ComputeControl > 
template<>
struct DataType< ::rctestpkg::ComputeControlRequest>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::ComputeControl >::value();
  }
  static const char* value(const ::rctestpkg::ComputeControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rctestpkg::ComputeControlResponse> should match 
// service_traits::MD5Sum< ::rctestpkg::ComputeControl > 
template<>
struct MD5Sum< ::rctestpkg::ComputeControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::ComputeControl >::value();
  }
  static const char* value(const ::rctestpkg::ComputeControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::ComputeControlResponse> should match 
// service_traits::DataType< ::rctestpkg::ComputeControl > 
template<>
struct DataType< ::rctestpkg::ComputeControlResponse>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::ComputeControl >::value();
  }
  static const char* value(const ::rctestpkg::ComputeControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCTESTPKG_MESSAGE_COMPUTECONTROL_H
