// Generated by gencpp from file rctestpkg/MPC_CC.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_MPC_CC_H
#define RCTESTPKG_MESSAGE_MPC_CC_H

#include <ros/service_traits.h>


#include <rctestpkg/MPC_CCRequest.h>
#include <rctestpkg/MPC_CCResponse.h>


namespace rctestpkg
{

struct MPC_CC
{

typedef MPC_CCRequest Request;
typedef MPC_CCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MPC_CC
} // namespace rctestpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rctestpkg::MPC_CC > {
  static const char* value()
  {
    return "7ee2ffc9de4aa168b06f3b4ade84ca37";
  }

  static const char* value(const ::rctestpkg::MPC_CC&) { return value(); }
};

template<>
struct DataType< ::rctestpkg::MPC_CC > {
  static const char* value()
  {
    return "rctestpkg/MPC_CC";
  }

  static const char* value(const ::rctestpkg::MPC_CC&) { return value(); }
};


// service_traits::MD5Sum< ::rctestpkg::MPC_CCRequest> should match 
// service_traits::MD5Sum< ::rctestpkg::MPC_CC > 
template<>
struct MD5Sum< ::rctestpkg::MPC_CCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MPC_CC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_CCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MPC_CCRequest> should match 
// service_traits::DataType< ::rctestpkg::MPC_CC > 
template<>
struct DataType< ::rctestpkg::MPC_CCRequest>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MPC_CC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_CCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rctestpkg::MPC_CCResponse> should match 
// service_traits::MD5Sum< ::rctestpkg::MPC_CC > 
template<>
struct MD5Sum< ::rctestpkg::MPC_CCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MPC_CC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_CCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MPC_CCResponse> should match 
// service_traits::DataType< ::rctestpkg::MPC_CC > 
template<>
struct DataType< ::rctestpkg::MPC_CCResponse>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MPC_CC >::value();
  }
  static const char* value(const ::rctestpkg::MPC_CCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCTESTPKG_MESSAGE_MPC_CC_H
