// Generated by gencpp from file rctestpkg/Headway.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_HEADWAY_H
#define RCTESTPKG_MESSAGE_HEADWAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rctestpkg
{
template <class ContainerAllocator>
struct Headway_
{
  typedef Headway_<ContainerAllocator> Type;

  Headway_()
    : h(0.0)
    , angle(0.0)
    , h_radial(0.0)  {
    }
  Headway_(const ContainerAllocator& _alloc)
    : h(0.0)
    , angle(0.0)
    , h_radial(0.0)  {
  (void)_alloc;
    }



   typedef double _h_type;
  _h_type h;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _h_radial_type;
  _h_radial_type h_radial;




  typedef boost::shared_ptr< ::rctestpkg::Headway_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rctestpkg::Headway_<ContainerAllocator> const> ConstPtr;

}; // struct Headway_

typedef ::rctestpkg::Headway_<std::allocator<void> > Headway;

typedef boost::shared_ptr< ::rctestpkg::Headway > HeadwayPtr;
typedef boost::shared_ptr< ::rctestpkg::Headway const> HeadwayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rctestpkg::Headway_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rctestpkg::Headway_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rctestpkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rctestpkg': ['/home/ubuntu/phil_catkin_ws/src/rctestpkg/msg'], 'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::Headway_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rctestpkg::Headway_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::Headway_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rctestpkg::Headway_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::Headway_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rctestpkg::Headway_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rctestpkg::Headway_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d6005cd199dedcc940134177d7d87ef";
  }

  static const char* value(const ::rctestpkg::Headway_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d6005cd199dedccULL;
  static const uint64_t static_value2 = 0x940134177d7d87efULL;
};

template<class ContainerAllocator>
struct DataType< ::rctestpkg::Headway_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rctestpkg/Headway";
  }

  static const char* value(const ::rctestpkg::Headway_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rctestpkg::Headway_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 h\n\
float64 angle\n\
float64 h_radial\n\
";
  }

  static const char* value(const ::rctestpkg::Headway_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rctestpkg::Headway_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.h);
      stream.next(m.angle);
      stream.next(m.h_radial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Headway_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rctestpkg::Headway_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rctestpkg::Headway_<ContainerAllocator>& v)
  {
    s << indent << "h: ";
    Printer<double>::stream(s, indent + "  ", v.h);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "h_radial: ";
    Printer<double>::stream(s, indent + "  ", v.h_radial);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RCTESTPKG_MESSAGE_HEADWAY_H
