// Generated by gencpp from file rctestpkg/MPC_LK.msg
// DO NOT EDIT!


#ifndef RCTESTPKG_MESSAGE_MPC_LK_H
#define RCTESTPKG_MESSAGE_MPC_LK_H

#include <ros/service_traits.h>


#include <rctestpkg/MPC_LKRequest.h>
#include <rctestpkg/MPC_LKResponse.h>


namespace rctestpkg
{

struct MPC_LK
{

typedef MPC_LKRequest Request;
typedef MPC_LKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MPC_LK
} // namespace rctestpkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rctestpkg::MPC_LK > {
  static const char* value()
  {
    return "07ec41d26dcbce48a88bfe9b463548bd";
  }

  static const char* value(const ::rctestpkg::MPC_LK&) { return value(); }
};

template<>
struct DataType< ::rctestpkg::MPC_LK > {
  static const char* value()
  {
    return "rctestpkg/MPC_LK";
  }

  static const char* value(const ::rctestpkg::MPC_LK&) { return value(); }
};


// service_traits::MD5Sum< ::rctestpkg::MPC_LKRequest> should match 
// service_traits::MD5Sum< ::rctestpkg::MPC_LK > 
template<>
struct MD5Sum< ::rctestpkg::MPC_LKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MPC_LK >::value();
  }
  static const char* value(const ::rctestpkg::MPC_LKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MPC_LKRequest> should match 
// service_traits::DataType< ::rctestpkg::MPC_LK > 
template<>
struct DataType< ::rctestpkg::MPC_LKRequest>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MPC_LK >::value();
  }
  static const char* value(const ::rctestpkg::MPC_LKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rctestpkg::MPC_LKResponse> should match 
// service_traits::MD5Sum< ::rctestpkg::MPC_LK > 
template<>
struct MD5Sum< ::rctestpkg::MPC_LKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rctestpkg::MPC_LK >::value();
  }
  static const char* value(const ::rctestpkg::MPC_LKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rctestpkg::MPC_LKResponse> should match 
// service_traits::DataType< ::rctestpkg::MPC_LK > 
template<>
struct DataType< ::rctestpkg::MPC_LKResponse>
{
  static const char* value()
  {
    return DataType< ::rctestpkg::MPC_LK >::value();
  }
  static const char* value(const ::rctestpkg::MPC_LKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RCTESTPKG_MESSAGE_MPC_LK_H
